### ISSUE TITLE
Does not delete old logix browser

### ISSUE THREAD

**Issue by AlexW-578** [AlexW-578/CustomLogixBrowser#2]
Mod just spawns new browser when clicking the node browser button
rather than closing the old browser

**Comment by AlexW-578** [comment]
Looks more complicated than at first look

Notes:
- Look at FrooxEngine.Logix.LogixNodeSelector.OnAttach again
- Look at FrooxEngine.Logix.LogixTip.ToggleNodeSelector to see if i can hook into the __nodeSelector.Target

**Comment by art0007i** [comment]
Both issues #1 and #2 stem from the same root problem. This happens because you are deleting the original component of the logix picker. The logix tip will store a reference to the node browser but you are deleting it so it becomes null. Also then CustomiseLogixBrowser has their own OnAttach patch which happens to run after yours, and that one tries to access __instance which doesn't exist anymore because you deleted it. It's actually possible to patch the OnAttach method without destroying the original component using a ReferenceTranslator but it is a little bit more complex. For an example you can check out [CustomInspectors](https://github.com/art0007i/CustomInspectors/blob/master/CustomInspectors/CustomInspectors.cs#L42).

But the better solution would be to patch FrooxEngine.Logix.LogixTip.ToggleNodeSelector and don't touch OnAttach at all, because it's the only place where the LogixNodeSelector is ever created. With CustomInspectors I had to resort to OnAttach because the code for creating an inspector isn't really generalized at all and involves simply attaching the SceneInspector component and changing some properties of it after it is attached.

**Comment by AlexW-578** [comment]
Cool thank you!
Will have a look at this the next time I'm available to

**Comment by AlexW-578** [comment]
Thank you again for reminding me to fix this and for an idea of how to.
This and #1 should be fixed in the latest release.
